export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_ALL_NOTIFICATIONS = "DELETE_ALL_NOTIFICATIONS";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_S = "FETCH_USER_S";

export const NOTIFICATION = "NOTIFICATION";
